---
- name: Deploy LAMP on Ubuntu hosts
  hosts: ubuntu
  become: yes
  become_method: sudo
  
  pre_tasks:
  - name: Update apt repository cache, if necessary
    apt: update_cache=yes cache_valid_time=3600

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted
  
  tasks:
  - name: Install LAMP packages
    apt:
      state: present
      name:
      - apache2
      - mariadb-server
      - mariadb-client
      - php

  - name: Disable the firewall
    service: name=ufw state=stopped

  - name: Start Apache and MariaDB
    service: "name={{ item }} state=started enabled=yes"
    with_items:
    - apache2
    - mariadb

  - name: Enable Apache userdir module for home directory hosting
    apache2_module: name=userdir state=present
    notify: restart apache

  - name: create new user
    user:
      name: toast
      password: Secret555
      state: present
      shell: /bin/bash
      create_home: yes
  - name: change permissions on home directory
    file:
      path: /home/toast
      state: directory
      mode: '0755'
  - name: create directory
    file:
      path: /home/toast/public_html
      state: directory
      mode: '0755'
      owner: root
      group: root

  - name: copy file
    copy:
      src: /home/oobla/public_html/index.html
      remote_src: yes
      dest: /home/toast/public_html/index.html
      owner: root
      group: root
      mode: '0644'


